## cartridge.properties for cartridge app_sfra_react
#Sat Apr 23 15:30:11 CEST 2026
demandware.cartridges.app_sfra_react.multipleLanguageStorefront=true
demandware.cartridges.app_sfra_react.id=app_sfra_react